export default {
  LOGIN_START: 'LOGIN_START',
  LOGIN_FIRE: 'LOGIN_FIRE',
  GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
  STATE_ERROR: 'STATE_ERROR',
  CODE_ERROR: 'CODE_ERROR',
  RECEIVED_AUTH_TOKEN: 'RECEIVED_AUTH_TOKEN',
  AUTH_TOKEN_ERROR: 'AUTH_TOKEN_ERROR',
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  LOGOUT: 'LOGOUT'
}
